config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :projects 
  end

  root :to => "users#index"

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :projects_users, dependent: :destroy
	has_many :users, through: :projects_users

end

app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
  
  self.primary_key = :id
  belongs_to :project
  belongs_to :user

  after_destroy :delete_projects

  private
	def delete_projects
		project = Project.find(self.project_id)
		if project.users.count == 0
			project.destroy
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :projects_users, dependent: :destroy
	has_many :projects, through: :projects_users
	accepts_nested_attributes_for :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :get_user, only: [:new, :create, :index, :update, :edit, :show, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = @user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.find_or_initialize_by(project_params)
    if @project.new_record?
      respond_to do |format|
        if  @project.save
          @projects_user = ProjectsUser.new(:project_id => @project.id, :user_id => @user.id)
          @projects_user.save
          format.html { redirect_to user_path(@user), notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
          
      #proyect already asigned to this user, does not do anything
      if project_already_assigned?(@user, @project)
        redirect_to user_path(@user), notice: 'Project is already asigned to this user' 
      else
        #add relation between project and user
        @projects_user = ProjectsUser.new(:project_id => @project.id, :user_id => @user.id)
        @projects_user.save
        redirect_to user_path(@user), notice: "This project now has #{@project.users.length} working on it"
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to user_projects_path(@user), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end

    def get_user
      @user = User.find(params[:user_id])
    end

    def project_already_assigned?(user,project)
      projects = user.projects
      pa = projects.find{|p| p.id == project.id}
      not pa.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(:name => user_params[:name], :email => user_params[:email])
    respond_to do |format|
      if @user.save
        unless params[:user][:project][:name].blank?
          @project = Project.find_or_initialize_by(user_params[:project])
          @project.save
          @projects_user = ProjectsUser.new(:project_id => @project.id, :user_id => @user.id)
          @projects_user.save
        end
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(:name => user_params[:name], :email => user_params[:email])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :project => [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HasManyThrough</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for [@user, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', edit_user_project_path(@user, @project) %> |
<%= link_to 'Back', user_projects_path(@user) %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects of <%= @user.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', user_projects_path(@user,project) %></td>
        <td><%= link_to 'Edit', edit_user_project_path(@user, project) %></td>
        <td><%= link_to 'Destroy', [@user,project], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_user_project_path(@user) %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', user_projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
<p>
<%= link_to 'Edit', edit_user_project_path(@user, @project) %> |
<%= link_to 'Back', user_path(@user) %>
</p>
<strong>People involved in this project:</strong><br><br>
<table>
<thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>

    </tr>
  </thead>
  <tbody>
<% @project.users.each do |user| %>
<tr>
	<th>
	<%= link_to user.name, user_path(user) %>
	</th>
	<th>
	<%= link_to 'Delete user', "#" %>
	</th>
</tr>
<% end %>
</tbody>
</table>
<br>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <%= f.fields_for :project do | project_form | %>
    <div class="field">
      <%= project_form.label :project_name %><br>
      <%= project_form.text_field :name %>
    </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>



<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<table>
	<thead>
	  <tr>
	    <th>Projects:</th>
	    <th colspan="3"></th>
	  </tr>
	</thead>
  <tbody>
		<% @user.projects.each do |project| %>
		<tr>
			<td><%= project.name %></td>
			<td><%= link_to 'Show', user_project_path(@user,project) %></td>
      <td><%= link_to 'Edit', edit_user_project_path(@user, project) %></td>
      <td><%= link_to 'Destroy', [@user,project], method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %> 
  </tbody>
</table>
<p>
<%= link_to 'Add project', new_user_project_path(@user) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>